version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - story-generator

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
    networks:
      - story-generator

networks:
  story-generator:
    driver: bridge